/*
 * VERSION
 * Les Ourses Ã  plumes
 * Javascript Wrap
 * Required jQuery Library
 * ver. 0.0.2
 *
 */
 
/* ------------------------------------------------------------------ */
/* # TEST */
/* ------------------------------------------------------------------ */

/* Below is temporary bullshit ; don't use */

var tb1 = "\t\t<div id='toolbar' class='hide-for-print hide'>\n\t\t\t\t<div class='top-bar' data-topbar>\n\t\t\t\t\t<ul class='title-area'>\n\t\t\t\t\t\t<li class='name'>\n\t\t\t\t\t\t\t<h1><a href='#toolbar'>Dev Toolbar</a></h1>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t</ul>\n\t\t\t\t\t<section class='top-bar-section'>\n\t\t\t\t\t\t<nav class='toolbar-nav'>\n\t\t\t\t\t\t\t<ul class='right'>\n";
var tb2 = "\t\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='kitchen_sink'>Kitchen Sink</a></li>\n\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_null_links_toggle'>Null Links</a></li>\n\t\t\t\t\t\t\t\t<li class='has-dropdown'>\n\t\t\t\t\t\t\t\t\t<a href='javascript:void(0)'>CSS Debug</a>\n\t\t\t\t\t\t\t\t<ul class='dropdown'>\n\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_icons_toggle'>Icons</a></li>\n\t\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_nav_pane_toggle'>Nav Pane</a></li>\n\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_fast_nav_toggle'>Fast Nav</a></li>\n\t\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_site_nav_toggle'>Site Nav</a></li>\n\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_orbit_slider_toggle'>Orbit Slider</a></li>\n";
var tb3 = "\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_breadcrumbs_toggle'>Breadcrumbs</a></li>\n\t\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_accessibility_toggle'>Accessibility</a></li>\n\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_user_account_toggle'>User Account</a></li>\n\t\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_article_toggle'>Articles</a></li>\n\t\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_articles_list_toggle'>Articles List</a></li>\n\t\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_debug_comment_list_toggle'>Comments</a></li>\n\t\t\t\t\t\t\t\t\t</ul>\n\t\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_css_fx_toggle'>CSS effects</a></li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' id='_toolbar_stick_toggle'>Toolbar</a></li>\n";
var tb4 = "\t\t\t\t\t\t\t<li><span class='hide'>Close</span><a href='javascript:void(0)' class='close'></a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t</nav>\n\t\t\t\t\t</section>\n\t\t\t</div>\n\t\t\t</div>\n";

$("#root").prepend("\n" + tb1 + tb2 + tb3 + tb4);

var tt = "\t\t\t<h1 class='text-center print-only'>Les Ourses &agrave; plumes</h1>\n\t\t\t<h4 class='text-center print-only'>http://www.ourses-plumes.fr</h4>\n";

var sb1 = "\t\t\t<!--Nav Pane-->\n\t\t\t<aside class='nav-pane text-center hide-for-print'>\n\t\t\t\t<h2 class='hide'>Navigation interne</h2>\n\t\t\t\t<h3 class='hide'>Fonctionnalit&eacute;s</h3>\n\t\t\t\t<!--Search-->\n\t\t\t\t<h4 class='hide'>Recherche</h4>\n\t\t\t\t<div id='_search_form' class='row collapse search'>\n\t\t\t\t\t<div class='column'>\n\t\t\t\t\t\t<input type='text' placeholder='Rechercher&hellip;'>\n\t\t\t\t\t</div>\n\t\t\t\t\t<div class='hide'>\n\t\t\t\t\t\t<button class='button postfix'>Rechercher</button>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t\t<!--Logo-->\n\t\t\t\t<div class='logo'>\n\t\t\t\t\t<a href='#main' data-show='home'><span></span></a>\n\t\t\t\t</div>\n";
var sb2 = "\t\t\t\t<!--Connect Launcher-->\n\t\t\t\t<h4 class='connect-launcher'><a href='javascript:void(0);' data-reveal-id='_connect_modal' data-reveal>Connexion</a></h4>\n\t\t\t\t<!--Connect Modal-->\n\t\t\t\t<div id='_connect_modal' class='reveal-modal small-modal' data-reveal>\n\t\t\t\t\t<h4>Se connecter</h4>\n\t\t\t\t\t<form data-abide>\n\t\t\t\t\t\t<fieldset>\n\t\t\t\t\t\t\t<legend>Authentification</legend>\n\t\t\t\t\t\t\t<div class='row collapse'>\n\t\t\t\t\t\t\t\t<div class='column small-12'>\n\t\t\t\t\t\t\t\t\t<input id='user_login' type='text' placeholder='Nom d&rsquo;utilisatrice ou adresse e-mail' required pattern='alpha'>\n\t\t\t\t\t\t\t\t\t<small class='error'>Identifiant requis&nbsp;!</small>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<div class='column small-8'>\n\t\t\t\t\t\t\t\t\t<input id='user_password' type='password' placeholder='Mot de passe' required pattern='alpha'>\n\t\t\t\t\t\t\t\t\t<small class='error'>Mot de passe requis&nbsp;!</small>\n\t\t\t\t\t\t\t\t</div>\n";
var sb3 = "\t\t\t\t\t\t\t\t<div class='column small-4'>\n\t\t\t\t\t\t\t\t\t<button class='connect-switch button small postfix'>Connexion</button>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t</fieldset>\n\t\t\t\t\t</form>\n\t\t\t\t\t<a class='close-reveal-modal'></a>\n\t\t\t\t</div>\n\t\t\t\t<!--User Nav-->\n\t\t\t\t<nav class='user-nav hide'>\n\t\t\t\t\t<h3 class='hide'>Menu utilisateur</h3>\n\t\t\t\t\t<h4 class='user-name'>Nadejda</h4>\n\t\t\t\t\t<ul class='clearfix'>\n\t\t\t\t\t\t<li><span class='picture medium' data-image='usr/usr-nadejda.jpg'>Image</span></li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='user-profile'>Mon profil</a></li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>R&eacute;diger un article</a></li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Publier un article</a></li>\n\t\t\t\t\t\t<li class='small'><a href='javascript:void(0)' class='disabled'><s>Modifier les cat&eacute;gories</s></a></li>\n";
var sb4 = "\t\t\t\t\t\t<li class='small'><a href='javascript:void(0)' class='disabled'><s>Modifier les rubriques</s></a></li>\n\t\t\t\t\t\t<li><a href='accounts.html' data-show='user-list'>Lister les comptes</a></li>\n\t\t\t\t\t\t<li><a href='bug-tracker.html' data-show='bug-tracker'>Signaler un bug</a></li>\n\t\t\t\t\t\t<li class='text-large'><a href='javascript:void(0)' class='connect-switch no-current red'>D&eacute;connexion</a></li>\n\t\t\t\t\t</ul>\n\t\t\t\t</nav>\n\t\t\t\t<hr>\n\t\t\t\t<!--Main Navigation-->\n\t\t\t\t<h3 class='hide'>Menu principal</h3>\n\t\t\t\t<h4 class='hide'>Sections</h4>\n\t\t\t\t<nav class='main-nav'>\n\t\t\t\t\t<ul>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='home'>&Eacute;dito</a></li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='latest'>&Agrave; la une</a></li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='articles 'data-roll='sub-list'>Articles</a></li>\n";
var sb5 = "\t\t\t\t\t\t<li class='sub-list'>\n\t\t\t\t\t\t\t<h5 class='hide'>Cat&eacute;gories</h5>\n\t\t\t\t\t\t\t<ul class='hide'>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Br&egrave;ves</a></li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Reportages</a></li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Dossiers</a></li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Spotlights</a></li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Interviews</a></li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Tribunes</a></li>\n\t\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Revues du web</a></li>\n\t\t\t\t\t\t\t</ul>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='agenda'>Agenda</a></li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled' >Nos amies</a></li>\n";
var sb6 = "\t\t\t\t\t\t<li><a href='mailto:oursesaplumes@gmail.com' class='no-current'>Contact</a></li>\n\t\t\t\t\t</ul>\n\t\t\t\t</nav>\n\t\t\t</aside>\n";

$("#main").prepend("\n" + tt + sb1 + sb2 + sb3 + sb4 + sb5 + sb6);

var hd1 = "\t\t\t\t<!--Header-->\n\t\t\t\t<header class='header text-center hide-for-print'>\n\t\t\t\t\t<!--Fast Nav-->\n\t\t\t\t\t<h5 class='hide'>Rubriques</h5>\n\t\t\t\t\t<nav class='fast-nav'>\n\t\t\t\t\t\t<ul class='inline-list'>\n\t\t\t\t\t\t\t<li class='orange'><a href='javascript:void(0)' class='disabled'>Luttes</a></li>\n\t\t\t\t\t\t\t<li class='magenta'><a href='javascript:void(0)' class='disabled'>Nos corps, nous-m&ecirc;mes</a></li>\n\t\t\t\t\t\t\t<li class='red'><a href='javascript:void(0)' class='disabled'>Intersectionnalit&eacute;</a></li>\n\t\t\t\t\t\t\t<li class='blue'><a href='javascript:void(0)' class='disabled'>International</a></li>\n\t\t\t\t\t\t\t<li class='cyan'><a href='javascript:void(0)' class='disabled'>&Eacute;ducation &amp; Culture</a></li>\n\t\t\t\t\t\t\t<li class='yellow'><a href='javascript:void(0)' class='disabled'>Id&eacute;es</a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t</nav>\n";
var hd2 = "\t\t\t\t\t<hr class='hide'>\n\t\t\t\t\t<!--News List-->\n\t\t\t\t\t<h2 class='hide'>Actualit&eacute;s</h2>\n\t\t\t\t\t<div class='news-list hide-for-small'>\n\t\t\t\t\t\t<ul data-orbit data-options='\n\t\t\t\t\t\t\tanimation_speed: 375;\n\t\t\t\t\t\t\tslide_number_text: sur;\n\t\t\t\t\t\t\tslide_number: false;\n\t\t\t\t\t\t\tbullets: false;\n\t\t\t\t\t\t\ttimer: false;\n\t\t\t\t\t\t\t'>\n\t\t\t\t\t\t\t<li class=''>\n\t\t\t\t\t\t\t\t<div class='orbit-headline text-center'>\n\t\t\t\t\t\t\t\t\t<h1>Les Ourses &agrave; plumes</h1>\n\t\t\t\t\t\t\t\t\t<h6>Gabarit HTML ver. Alpha 2</h6>\n\t\t\t\t\t\t\t\t\t<!--<h4 style='margin-top: -1rem; margin-bottom: 1rem;'>webzine féministe</h4>-->\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n";
var hd3 = "\t\t\t\t\t\t\t<li class='orange'>\n\t\t\t\t\t\t\t\t<div class='orbit-headline text-center'>\n\t\t\t\t\t\t\t\t\t<blockquote class='text-large'>\n\t\t\t\t\t\t\t\t\t\t&ldquo;&#8239;Simple, forte, aimant l&rsquo;art et l&rsquo;id&eacute;al, brave et libre aussi, la femme de demain ne voudra ni dominer, ni &ecirc;tre domin&eacute;e.&#8239;&rdquo;\n\t\t\t\t\t\t\t\t\t\t<cite>Louise Michel <small>(1830-1905)</small></cite>\n\t\t\t\t\t\t\t\t\t</blockquote>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li class='black'>\n\t\t\t\t\t\t\t\t<div class='orbit-image'>\n\t\t\t\t\t\t\t\t\t<img src='img/pub/afp_mlf_1982_paris.jpg' alt='AFP MLF 1982 Paris'>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<div class='orbit-caption'>\n\t\t\t\t\t\t\t\t\tManifestation du MLF contre le travail &agrave; temps partiel, 6 mars 1982 &agrave; Paris, AFP-FAGET\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n";
var hd4 = "\t\t\t\t\t\t\t<li class='magenta'>\n\t\t\t\t\t\t\t\t<div class='orbit-headline'>\n\t\t\t\t\t\t\t\t\t<blockquote class='text-large'>\n\t\t\t\t\t\t\t\t\t\t&ldquo;&#8239;F&eacute;minisme. Oui, je crois qu&rsquo;il est convenable, avant que de faire un enfant &agrave; une femme, de lui demander si elle le veut.&#8239;&rdquo;\n\t\t\t\t\t\t\t\t\t\t<cite>Jules Renard <small>(1864-1910)</small></cite>\n\t\t\t\t\t\t\t\t\t</blockquote>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li class='black'>\n\t\t\t\t\t\t\t\t<div class='orbit-image'>\n\t\t\t\t\t\t\t\t\t<img src='img/pub/afp_femen_2013_madrid.jpg' alt='AFP Femen 2013 Madrid' />\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<div class='orbit-caption'>\n\t\t\t\t\t\t\t\t\tMilitantes du Femen devant une &eacute;glise, 23 d&eacute;cembre 2013 &agrave; Madrid, P.-P. Marcou pour AFP\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n";
var hd5 = "\t\t\t\t\t\t\t<li class='red'>\n\t\t\t\t\t\t\t\t<div class='orbit-headline'>\n\t\t\t\t\t\t\t\t\t<blockquote class='text-large'>\n\t\t\t\t\t\t\t\t\t\t&ldquo;&#8239;Un homme sur deux est une femme.&#8239;&rdquo;\n\t\t\t\t\t\t\t\t\t\t<cite>Slogan f&eacute;ministe, Ao&ucirc;t 1970</cite>\n\t\t\t\t\t\t\t\t\t</blockquote>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li class='black'>\n\t\t\t\t\t\t\t\t<div class='orbit-image'>\n\t\t\t\t\t\t\t\t\t<img src='img/pub/gouesse_femmes_solidaires_2011_paris.jpg' alt='Gouesse Femmes solidaires 2011 Paris'>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<div class='orbit-caption'>\n\t\t\t\t\t\t\t\t\tFemmes solidaires, Journ&eacute;e internationale de la femme, 5 mars 2011 &agrave; Paris, Julien Gouesse\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n";
var hd6 = "\t\t\t\t\t\t\t<li class='cyan'>\n\t\t\t\t\t\t\t\t<div class='orbit-headline'>\n\t\t\t\t\t\t\t\t\t<blockquote class='text-large text-center'>\n\t\t\t\t\t\t\t\t\t\t&ldquo;&#8239;Le nouvel homme a r&eacute;solu &agrave; sa fa&ccedil;on le nouveau partage des t&acirc;ches&#8239;: Occupe-toi de tout et je ferai le reste.&#8239;&rdquo;\n\t\t\t\t\t\t\t\t\t\t<cite>Mich&egrave;le Fitoussi, &Eacute;ditorialiste &agrave; Elle</cite>\n\t\t\t\t\t\t\t\t\t</blockquote>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t<li class='black'>\n\t\t\t\t\t\t\t\t<div class='orbit-image'>\n\t\t\t\t\t\t\t\t\t<img src='img/pub/mouzon_la_barbe_2012_paris.jpg' alt='Mouzon La Barbe 2012 Paris' />\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<div class='orbit-caption'>\n\t\t\t\t\t\t\t\t\tAction du groupe f&eacute;ministe La Barbe, 14 juillet 2012 &agrave; Paris (Place de la Nation), C&eacute;line Mouzon\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n";
var hd7 = "\t\t\t\t\t\t</ul>\n\t\t\t\t\t</div>\n\t\t\t\t\t<hr class='hide'>\n\t\t\t\t\t<!--Breadcrumbs-->\n\t\t\t\t\t<h4 class='hide'>Fil d&rsquo;Ariane</h4>\n\t\t\t\t\t<ul class='breadcrumbs'>\n\t\t\t\t\t\t<li class='unavailable'>Les Ourses &agrave; plumes</li>\n\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='about'>&Agrave; propos</a></li>\n\t\t\t\t\t\t<li class='current'><a href='javascript:void(0)'>Avertissement</a></li>\n\t\t\t\t\t</ul>\n\t\t\t\t\t<!--Accessibility-->\n\t\t\t\t\t<h4 class='hide'>Accessibilit&eacute;</h4>\n\t\t\t\t\t<div class='accessibility'>\n\t\t\t\t\t\t<ul class='inline-list'>\n\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='icon-textinc small'>Plus grand</a></li>\n\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='icon-textdec small'>Plus petit</a></li>\n\t\t\t\t\t\t\t<li><a href='javascript:print()'><span class='icon-print small'>Imprimer</span></a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t</div>\n\t\t\t\t</header>\n\t\t\t\t<hr>\n";

$(".main-pane").prepend("\n" + hd1 + hd2 + hd3 + hd4 + hd5 + hd6 + hd7);

var ft1 = "\t\t\t\t<hr class='hide'>\n\t\t\t\t<!--Footer-->\n\t\t\t\t<footer class='footer text-center hide-for-print'>\n\t\t\t\t\t<!--Site Navigation-->\n\t\t\t\t\t<h2 class='hide'>Navigation externe</h2>\n\t\t\t\t\t<h3 class='hide'>Menu de site</h3>\n\t\t\t\t\t<nav class='site-nav'>\n\t\t\t\t\t\t<ul>\n\t\t\t\t\t\t\t<li><a href='javascript:void(0)' data-show='about'>&Agrave; propos</a></li>\n\t\t\t\t\t\t\t<li><a href='javascript:void(0)' class='disabled'>Mentions l&eacute;gales</a></li>\n\t\t\t\t\t\t\t<li class='no-bullet'><a href='mailto:oursesaplumes@gmail.com' class='icon-mail large white no-current'>Contact</a></li>\n\t\t\t\t\t\t\t<li class='no-bullet'><a href='javascript:void(0)' class='icon-twitter large white disabled'>Twitter</a></li>\n\t\t\t\t\t\t\t<li class='no-bullet'><a href='javascript:void(0)' class='icon-facebook large white disabled'>Facebook</a></li>\n\t\t\t\t\t\t</ul>\n\t\t\t\t\t</nav>\n";
var ft2 = "\t\t\t\t\t<!--Copyright-->\n\t\t\t\t\t<div class='end-notes'>Copyright &copy; 2014 Les Ourses &agrave; plumes</div>\n\t\t\t\t</footer>\n\t\t\t</div>\n";

$(".main-pane").append("\n" + ft1 + ft2);
