create table folder (
  id                        bigint GENERATED BY DEFAULT AS SEQUENCE folder_seq  not null,
  title                     varchar(255),
  hash                     varchar(255),
  desc						varchar(2000),
  constraint pk_folder primary key (id))
;